# Generated by Django 4.2.16 on 2025-06-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp_secret',
        ),
    ]
