# Generated by Django 4.2.16 on 2025-05-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='invite_code',
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='role',
            field=models.CharField(choices=[('executor', 'Исполнитель'), ('responsible', 'Ответственный')], max_length=12, verbose_name='Роль в задаче'),
        ),
        migrations.AlterField(
            model_name='userprojectrole',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Менеджер'), ('leader', 'Руководитель')], max_length=10, verbose_name='Роль на проекте'),
        ),
    ]
