# Generated by Django 4.2.16 on 2025-03-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='admin_code',
            new_name='invite_code',
        ),
        migrations.AlterField(
            model_name='userprojectrole',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('partner', 'Заказчик'), ('manager', 'Менеджер'), ('leader', 'Руководитель')], max_length=10),
        ),
    ]
