# Generated by Django 4.2.16 on 2025-05-26 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_userorganizationrole_can_edit'),
        ('projects', '0003_remove_project_invite_code_alter_taskassignment_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-created_at'], 'verbose_name': 'История изменений', 'verbose_name_plural': 'История изменений'},
        ),
        migrations.AddField(
            model_name='history',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('org_create', 'Создание организации'), ('org_update', 'Изменение организации'), ('project_create', 'Создание проекта'), ('project_update', 'Изменение проекта'), ('project_status', 'Изменение статуса проекта'), ('task_create', 'Создание задачи'), ('task_update', 'Изменение задачи'), ('task_status', 'Изменение статуса задачи'), ('task_deadline', 'Изменение сроков задачи'), ('subtask_create', 'Создание подзадачи'), ('subtask_update', 'Изменение подзадачи'), ('subtask_status', 'Изменение статуса подзадачи'), ('subtask_deadline', 'Изменение сроков подзадачи'), ('member_add', 'Добавление участника'), ('member_remove', 'Удаление участника'), ('role_change', 'Изменение роли'), ('comment_add', 'Добавление комментария'), ('attachment_add', 'Добавление вложения')], max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('discussion', 'В обсуждении'), ('implementation', 'В работе'), ('correction', 'В исправлении'), ('completed', 'Завершено'), ('postponed', 'Отложено')], db_index=True, default='new', max_length=50, verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('task', 'Задача'), ('development', 'Разработка'), ('idea', 'Идея'), ('research', 'Исследование')], db_index=True, default='task', max_length=50, verbose_name='Тип задачи'),
        ),
        migrations.DeleteModel(
            name='TaskDependency',
        ),
    ]
