# Generated by Django 4.2.16 on 2025-06-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_history_options_history_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='subtask',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='subtask',
        ),
        migrations.AddField(
            model_name='checklist',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
    ]
