# Generated by Django 4.2.16 on 2025-03-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='code',
            new_name='invite_code',
        ),
    ]
