# Generated by Django 4.2.16 on 2025-05-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganizationrole',
            name='can_edit',
            field=models.BooleanField(default=False, verbose_name='Можно редактировать'),
        ),
    ]
