# Generated by Django 4.2.16 on 2025-05-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
